### ISSUE TITLE
Correct way to make cancellation 

### ISSUE THREAD

**Issue by mralessio** [insolor/async-tkinter-loop#10]
Hello! Thanks you for your helper!

What is the proper way to cancel the process when closing the Tkinter window?

For example,  
```
root = Tk()
...

def on_closing(): 
    root.quit()
    root.destroy()

root.protocol('WM_DELETE_WINDOW', on_closing)

async_mainloop(root)
```

After I close the window , the window itself closes, but process is still not finished.

**Comment by insolor** [comment]
Hi! I've published version 0.6.0, now you can kill an application using `.destroy()` method.

But I haven't managed yet to make `.quit()` method work properly. May be later I will fix it.

**Comment by insolor** [comment]
@mralessio please test on the 0.6.0 version. If it works for you, I'll close the issue.

**Comment by mralessio** [comment]
@insolor, did a test. works very well for me now. Thanks a lot!

**Comment by insolor** [comment]
Thank you for the report, I didn't even know there was a problem with quitting of an application
