### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by bits-n-pieces-ch** [insolor/async-tkinter-loop#127]
in the example start_stop_counter.py I get a warning:

DeprecationWarning: There is no current event loop
  asyncio.get_event_loop_policy().get_event_loop().create_task(counter())

I belive it is in conjuntion with Python 3.13

**Comment by insolor** [comment]
I'll check this after Python 3.13.1 release (~ December 2024)

**Comment by insolor** [comment]
Actually, it shows warning on Python 3.12 too. I'll just update the example.

**Comment by insolor** [comment]
Fixed in #128
