### ISSUE TITLE
Support for Background Functions in async_mainloop

### ISSUE THREAD

**Issue by Mo-to** [insolor/async-tkinter-loop#133]
# Support for Background Update Functions in `async_mainloop`

First of all, thank you for sharing this library! It has been a big help in my project, and I truly appreciate you've shared this lib.

## Need
In my project, I encountered a scenario where I didn’t need an async function triggered by an element like a button press.  Instead, I needed a background update function that would run continuously and regularly perform updates. 

## Solution
Thanks to your work, I was able to achieve this fairly easy by a small tweak to your code. Specifically, by modifying the following section:

https://github.com/insolor/async-tkinter-loop/blob/7dd8f02033de3d9060e2be22d160294b5844edbc/async_tkinter_loop/async_tkinter_loop.py#L46-L55

**Modified Code:**
```python
def async_mainloop(root: tkinter.Tk, custom_coroutine) -> None:
    """
    A function, which is a substitute to the standard `root.mainloop()`.

    Args:
        root: tkinter root object
    """
    coroutines = [custom_coroutine, main_loop(root)]
    get_event_loop().run_until_complete(asyncio.gather(*coroutines))
```

This change allows me to pass a custom update function to `async_mainloop`. Here's an example of how I used it in my project:

**Example Usage:**
```python
async def update():
    """
    Demonstration update function
    """
    while True:
        print("Some task")
        await asyncio.sleep(1)

async_mainloop(root, update())
```

With this approach, I can easily run an asynchronous background task while using the `async_mainloop`. This is particularly useful for dynmic updates of the UI or performing other background tasks like webscraping.

### Request
Would you consider adding support for this use case to the library? I believe this feature would be a valuable addition for users who need to run background tasks alongside their Tkinter applications.

Thank you again for sharing your work, i hope i can give something back to the community with this! Let me know if you'd like further clarification or a pull request for this suggestion.

Best regards,  
Mo-to

**Comment by insolor** [comment]
There is no need in such modifications. Just use `loop.create_task()` to create background tasks. See https://github.com/insolor/async-tkinter-loop/blob/main/examples/start_stop_counter.py example. Just replace start/stop logic in this example with your infinite loop, and it will work.

**Comment by insolor** [comment]
Closing, because background tasks are already supported (through `loop.create_task()`)
